default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qa_development


test:
  <<: *default
  database: qa_test

production:
  <<: *default
  database: qa_production
  username: qa
  password: <%= ENV['QA_DATABASE_PASSWORD'] %>
